### ISSUE TITLE
update-catalog throws an exception

### ISSUE THREAD

**Issue by rudolphoa** [alexa/ask-cli#140]
When running the ask cli update-catalog command it consistently throws the following exception. Am using ask cli v2..1.1. Although I was getting the same error with v2.0.0 too

```
ask smapi upload-catalog -c <REDACTED> -f ./catalog.json
Upload (upload-id: <REDACTED>) created successfully. Upload starts...
  /usr/local/lib/node_modules/ask-cli/lib/clients/aws-client/s3-client.js:304
            S3Client.presignedPutObject(
                     ^

TypeError: S3Client.presignedPutObject is not a function
    at ParallelStream.uploadTask [as transform] (/usr/local/lib/node_modules/ask-cli/lib/clients/aws-client/s3-client.js:304:22)
    at ParallelStream._transform (/usr/local/lib/node_modules/ask-cli/lib/utils/stream-utility.js:41:18)
    at ParallelStream.Transform._read (_stream_transform.js:186:10)
    at ParallelStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at ParallelStream.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
```

**Comment by kakhaUrigashvili** [comment]
fixed in 2.2.0.
