### ISSUE TITLE
Set interaction model - SyntaxError: Unexpected token i in JSON at position 4

### ISSUE THREAD

**Issue by guilhermecaixeta** [alexa/ask-cli#203]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Set a new interaction model in alexa development console from my local skill

## Current Behavior

When the command is executed it's returned an error: SyntaxError: Unexpected token i in JSON at position 4

Command used:
ask smapi set-interaction-model -l en-US -g development -s my-skill-id -p user-admin --interaction-model "$(cat ./skill-package/interactionModels/custom/en-US.json)"

The entire debug console:
```
undefined:1
{   interactionModel: {     languageModel: {       invocationName: invocationName
    ^

SyntaxError: Unexpected token i in JSON at position 4
    at JSON.parse (<anonymous>)
    at _loadJson (my-pc\AppData\Roaming\npm\node_modules\ask-cli\lib\commands\smapi\smapi-command-handler.js:43:21)
    at _loadValue (my-pc\AppData\Roaming\npm\node_modules\ask-cli\lib\commands\smapi\smapi-command-handler.js:48:52)
    at my-pc\AppData\Roaming\npm\node_modules\ask-cli\lib\commands\smapi\smapi-command-handler.js:69:35
    at Array.forEach (<anonymous>)
    at _mapToParams (my-pc\AppData\Roaming\npm\node_modules\ask-cli\lib\commands\smapi\smapi-command-handler.js:52:32)
    at smapiCommandHandler (my-pc\AppData\Roaming\npm\node_modules\ask-cli\lib\commands\smapi\smapi-command-handler.js:110:26)
    at Command.<anonymous> (my-pc\AppData\Roaming\npm\node_modules\ask-cli\lib\commands\smapi\smapi-commander.js:86:51)
    at Command.listener (my-pc\AppData\Roaming\npm\node_modules\ask-cli\node_modules\commander\index.js:370:29)
    at Command.emit (events.js:315:20)
```

## Steps to Reproduce (for bugs)

run the command in powershell core 7: 

ask smapi set-interaction-model -l en-US -g development -s my-skill-id -p user-admin --interaction-model "$(cat ./skill-package/interactionModels/custom/en-US.json)"

## Your Environment and Context

* ask-cli version: 2.7
* Operating System and version: Windows 10 pro
* Node.js version used for development: 14.2
* NPM version used for development: 6.14

**Comment by kakhaUrigashvili** [comment]
@guilhermecaixeta I believe there is no 'cat' command on Windows. you can use 'type' instead. You can also provide file path like this
`--interaction-model file:skill-package/interactionModels/custom/en-US.json`

if starts with 'file:' the cli will try to load and parse the file. It works for options that have [JSON] flag when you run `-h`. This was recently added.
