### ISSUE TITLE
ask new:  crashes  if target directory not writable

### ISSUE THREAD

**Issue by allenabc** [alexa/ask-cli#350]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior

The script should detect the target directory is not writable quit with a message like 
directory XX not writable please retry in a writable directory

## Current Behavior

allen@allenComputer:/usr/bin$ ask new
Please follow the wizard to start your Alexa skill project ->
? Choose the programming language you will use to code your skill:  NodeJS
? Choose a method to host your skill's backend resources:  Alexa-hosted skills
  Host your skill code by Alexa (free).
? Choose the default locale for your skill:  en-US
? Choose the default region for your skill:  us-east-1
? Please type in your skill name:  helloworldone
? Please type in your folder name for the skill project (alphanumeric):  helloworldone
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/usr/bin/helloworldone'
    at Object.mkdirSync (fs.js:757:3)
    at _generateProjectDirectory (/usr/local/lib/node_modules/ask-cli/lib/controllers/hosted-skill-controller/clone-flow.js:37:6)
    at Object.generateProject (/usr/local/lib/node_modules/ask-cli/lib/controllers/hosted-skill-controller/clone-flow.js:29:3)
    at getHostedSkillMetadata (/usr/local/lib/node_modules/ask-cli/lib/controllers/hosted-skill-controller/index.js:66:17)
    at smapiClient.skill.alexaHosted.getAlexaHostedSkillMetadata (/usr/local/lib/node_modules/ask-cli/lib/controllers/hosted-skill-controller/index.js:104:7)
    at _normalizeSmapiResponse (/usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:169:11)
    at _normalizeSmapiResponse (/usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:189:3)
    at httpClient.request (/usr/local/lib/node_modules/ask-cli/lib/clients/smapi-client/index.js:168:9)
    at Request.requestLib [as _callback] (/usr/local/lib/node_modules/ask-cli/lib/clients/http-client.js:64:12)
    at Request.self.callback (/usr/local/lib/node_modules/ask-cli/node_modules/request/request.js:185:22)
allen@allenComputer:/usr/bin$ 

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
2.20.0
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@allenabc  "Error: EACCES: permission denied, mkdir '/usr/bin/helloworldone'" is not intuitive ?

**Comment by allenabc** [comment]
Stack traces have no place in production code.

**Comment by kakhaUrigashvili** [comment]
@allenabc Would you like to contribute by fixing this bug?

I think we just need to add another validation inside of this method
https://github.com/alexa/ask-cli/blob/develop/lib/commands/new/ui.js#L81

It also seems like getProjectFolderName method is created in 2 files and it is identical. May be makes sense to move to some common file.

**Comment by allenabc** [comment]
Considering  helping out. It will take me some time to get setup. In the mean time I dont want to block progress.

**Comment by kakhaUrigashvili** [comment]
@allenabc no worries. I will open a PR with the fix shortly.
