### ISSUE TITLE
Typo in suggested default index.handler value when doing askx init

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When doing askx init the index.handler value defaults to:

index.hanlder

which includes a typo. If you use the defaults then your Lambda will be broken ad reporting this on Cloudwatch:

```
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.hanlder is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.hanlder is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)",
        "    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"
    ]
}
```

## Current Behavior

**CLI Snapshot**

```
> askx init
This utility will walk you through creating an ask-resources.json file
to help deploy your skill. This only covers the most common attributes 
and will suggest sensible defaults using AWS Lambda as your endpoint.

This will utilize your 'default' ASK profile. Run with "--profile" 
to specify a different profile.

Press ^C at any time to quit.

? ask-resources.json already exists in current directory. Do you want to overwrite it?  Yes
? Skill Id (leave empty to create one):  amzn1.ask.skill.5d7024e1-xxxxxxxxxx
? Skill package path:  ./skill-package
? Lambda code path (for default region):  code
? Use AWS CloudFormation to deploy Lambda?  No
? Lambda runtime:  nodejs10.x
? Lambda handler:  index.hanlder
```

## Your Environment and Context

* ask-cli version: 0.11.0
* Operating System and version:
* Node.js version used for development: 11.14.0
* NPM version used for development: 6.7.0

**Comment by RonWang** [comment]
Hi @germanviscuso , this has been solved in this commit 7134b4635b4ed1d0c075239c58bca19619babd57. Thanks for letting us know this problem, and will close this issue with the fix! Please feel free to let us know when you meet any problem~
